// core/backend/lib/c_header.dart
//
// Generates a C header declaring every function in a DCModule, so C, Rust,
// Python (ctypes/cffi), Go (cgo), Zig and anything else that speaks the C
// ABI can call into DCDart. See docs/decisions/0034-c-header-emission.md.
//
// WHY THIS IS THE WHOLE FFI STORY (in the outbound direction)
//
// DCDart already emits plain C-ABI object files: `core/backend/m0-target.md`
// §1 deliberately specifies no `dso_local` and no custom calling convention,
// which is why `examples/demo-collatz/main.c` can `extern uint64_t
// collatzSteps(uint64_t)` and just link. So nothing about the OBJECT needed
// to change for FFI — the missing piece was purely declarative: callers had
// to hand-write those `extern` lines and keep them in sync with the Dart
// source by eye. A wrong hand-written prototype is not a compile error, it
// is silent ABI corruption. This emitter removes that class of bug by
// deriving the declarations from the same DC-IR the object file is emitted
// from.
//
// This covers DCDart-called-FROM-C. The other direction (DCDart calling an
// arbitrary external C symbol) is a different, unsolved problem — see
// known-gaps.md GAP-0019.

import 'package:dc_ir/dc_ir.dart';

/// Thrown when a DC-IR type has no honest C spelling. Better a build error
/// naming the function than a header with a plausible-looking wrong type in
/// it, which would corrupt the ABI silently at the caller.
class CHeaderError implements Exception {
  final String message;
  const CHeaderError(this.message);

  @override
  String toString() => 'CHeaderError: $message';
}

/// Emits the full text of a C header for [module].
///
/// [headerName] is used for the include guard (e.g. `ACCOUNT_H`).
String emitCHeader(DCModule module, {required String headerName}) {
  final guard = 'DCDART_$headerName';
  final buffer = StringBuffer();

  buffer.writeln('/* ${module.name} — generated by dcc --emit-header.');
  buffer.writeln(' *');
  buffer.writeln(' * Do not edit. Regenerate with:');
  buffer.writeln(' *   dcc build --mode bare <source>.dart -o <out>.o \\');
  buffer.writeln(' *     --emit-header <this file>');
  buffer.writeln(' *');
  buffer.writeln(' * These are ordinary C-ABI symbols: link the .o and call them.');
  buffer.writeln(' */');
  buffer.writeln('#ifndef $guard');
  buffer.writeln('#define $guard');
  buffer.writeln();
  buffer.writeln('#include <stdint.h>');
  buffer.writeln('#include <stddef.h>');
  buffer.writeln('#include <stdbool.h>');
  buffer.writeln();
  buffer.writeln('#ifdef __cplusplus');
  buffer.writeln('extern "C" {');
  buffer.writeln('#endif');
  buffer.writeln();

  // Struct definitions come first: a function signature may return one by
  // value (spec §6 / ADR-0011's @packed layout, ADR-0014's Result), and C
  // requires a complete type before it is used that way.
  final structs = _collectStructs(module);
  if (structs.isNotEmpty) {
    for (final struct in structs) {
      buffer.write(_emitStruct(struct));
      buffer.writeln();
    }
  }

  // An opaque handle for heap objects. C must never dereference one: the
  // object carries an ARC header (spec §3.1, u32 strong + u32 weak + ptr
  // cls) whose layout is explicitly not frozen, and touching the refcount
  // from C would corrupt it. Passing the pointer straight back to another
  // DCDart function is the only supported use.
  if (_usesHeapPointer(module)) {
    buffer.writeln('/* Opaque handle to an ARC-managed DCDart heap object.');
    buffer.writeln(' * Treat as a token: pass it back to DCDart functions,');
    buffer.writeln(' * never dereference it and never free() it. Its layout');
    buffer.writeln(' * (DCDART_SPEC.md §3.1) is not part of this ABI. */');
    buffer.writeln('typedef void *DCHeapRef;');
    buffer.writeln();
  }
  if (_usesWeakPointer(module)) {
    buffer.writeln('/* Opaque handle to a DCDart weak reference (ADR-0023). */');
    buffer.writeln('typedef void *DCWeakRef;');
    buffer.writeln();
  }

  for (final function in module.functions) {
    buffer.writeln(_emitDeclaration(function));
  }

  buffer.writeln();
  buffer.writeln('#ifdef __cplusplus');
  buffer.writeln('} /* extern "C" */');
  buffer.writeln('#endif');
  buffer.writeln();
  buffer.writeln('#endif /* $guard */');
  return buffer.toString();
}

/// One `returnType name(params);` line.
///
/// Built through [cDeclaratorOf] on the RETURN type, with `name(params)` as the
/// declarator, rather than as `"$ret $name($params)"`. For every ordinary
/// return type the two are the same string; for a function-pointer return they
/// are not, and only the first is valid C:
///
///     uint64_t (*chooser(uint64_t a0))(uint64_t);   // correct
///     uint64_t (*)(uint64_t) chooser(uint64_t a0);  // does not parse
///
/// C declarator syntax reads outward from the identifier, so a returned
/// function pointer wraps the whole call declarator. This was found by
/// compiling the emitted header (ADR-0060) rather than by reading it.
String _emitDeclaration(DCFunction function) {
  final params = <String>[];
  for (var i = 0; i < function.paramTypes.length; i++) {
    params.add(cDeclaratorOf(function.paramTypes[i], 'a$i', context: function.linkName));
  }
  // C's `f()` means "unspecified arguments", not "no arguments"; `f(void)`
  // is the one that actually type-checks a zero-arg call.
  final paramList = params.isEmpty ? 'void' : params.join(', ');
  return '${cDeclaratorOf(function.returnType, '${function.linkName}($paramList)', context: function.linkName)};';
}

String _emitStruct(DCStruct struct) {
  final buffer = StringBuffer();
  // Every DCDart struct reaching C is @packed (spec §6): dcc-lower requires
  // the annotation on every `extends Struct` subclass it lowers, and
  // ADR-0011 verified that layout byte-for-byte against a C reference. The
  // attribute is emitted so the C side agrees, rather than relying on the
  // two happening to pad identically.
  buffer.writeln('#if defined(_MSC_VER)');
  buffer.writeln('#  define DCDART_PACKED');
  buffer.writeln('#  pragma pack(push, 1)');
  buffer.writeln('#else');
  buffer.writeln('#  define DCDART_PACKED __attribute__((packed))');
  buffer.writeln('#endif');
  buffer.writeln('typedef struct {');
  for (final field in struct.fields) {
    buffer.writeln('  ${cDeclaratorOf(field.type, field.name, context: struct.name)};');
  }
  buffer.writeln('} DCDART_PACKED ${struct.name};');
  buffer.writeln('#if defined(_MSC_VER)');
  buffer.writeln('#  pragma pack(pop)');
  buffer.writeln('#endif');
  return buffer.toString();
}

/// One named declaration in C: a type and the identifier it declares.
///
/// For almost every DCType this is just `"$type $name"` — but C's declarator
/// syntax is not "type then name" in general, and a function pointer is the
/// case where that bites: the identifier goes INSIDE the parentheses
/// (`uint64_t (*f)(uint64_t)`), so pasting a name after `cTypeOf`'s
/// abstract-declarator spelling produces a header that does not compile.
/// Every place this emitter names a thing goes through here, so the shape is
/// decided once (ADR-0060).
String cDeclaratorOf(DCType type, String name, {required String context}) {
  if (type is DCFuncPtr) {
    final ret = cTypeOf(type.returnType, context: context);
    final ps = type.params.isEmpty
        ? 'void'
        : type.params.map((p) => cTypeOf(p.type, context: context)).join(', ');
    return '$ret (*$name)($ps)';
  }
  return '${cTypeOf(type, context: context)} $name';
}

/// Maps a DC-IR type to its C spelling.
///
/// [context] is the function or struct name, used only to make an error
/// message point at the offending declaration.
String cTypeOf(DCType type, {required String context}) {
  switch (type) {
    case DCVoid():
      return 'void';
    case DCBool():
      // DCBool is LLVM `i1`. C's `_Bool` is a full byte, and an i1 in a
      // signature is ABI-ambiguous (the high 7 bits are undefined), so
      // spelling this `bool` would produce a header that compiles, links,
      // and is silently wrong at the boundary — the exact failure this
      // emitter exists to prevent. No DCDart function signature can carry a
      // bool today (comparisons only ever feed CondBranch), so this is
      // unreachable rather than a limitation; if it ever becomes reachable,
      // the fix is to widen the ABI type deliberately, not to guess here.
      throw CHeaderError(
        '"$context": a DCDart bool cannot cross the C ABI. It lowers to '
        'LLVM i1, whose padding in a C `_Bool` is undefined. Return a '
        'u8 (0/1) instead.',
      );
    case DCInt(width: final width, signed: final signed):
      switch (width) {
        case IntWidth.w8:
          return signed ? 'int8_t' : 'uint8_t';
        case IntWidth.w16:
          return signed ? 'int16_t' : 'uint16_t';
        case IntWidth.w32:
          return signed ? 'int32_t' : 'uint32_t';
        case IntWidth.w64:
          return signed ? 'int64_t' : 'uint64_t';
        case IntWidth.wSize:
          // ptrdiff_t rather than ssize_t: ssize_t is POSIX, absent on MSVC,
          // and this header must compile on Windows too.
          return signed ? 'ptrdiff_t' : 'size_t';
      }
    case DCFloat(width: final width):
      // IEEE binary32/binary64 (ADR-0065) — C's `float`/`double` are the
      // same formats on every registry target, and both pass/return in
      // vector registers per the SysV and AAPCS64 ABIs, which is what the
      // LLVM signature already says. This case predates float codegen (it
      // was written for switch exhaustiveness) and became reachable when
      // ADR-0065 landed.
      return width == FloatWidth.w32 ? 'float' : 'double';
    case DCPointer(pointee: final pointee):
      // `void*` for a pointer-to-void, otherwise a real pointee type, so
      // Pointer<u32> comes out as uint32_t* and stays type-checked in C.
      final inner = cTypeOf(pointee, context: context);
      return inner == 'void' ? 'void *' : '$inner *';
    case DCHeapPointer():
      return 'DCHeapRef';
    case DCWeakPointer():
      return 'DCWeakRef';
    case DCFuncPtr(params: final params, returnType: final returnType):
      // (ADR-0060) A real C function-pointer type, spelled out, so a C caller
      // handed one by DCDart can actually call it.
      //
      // The `@owned` half of the DC-IR type is DELIBERATELY not represented:
      // C has no way to say it, and there is no annotation that would make a
      // C compiler enforce it. A C function passed where DCDart expects an
      // owned-consuming callback must release its argument, and nothing in
      // this header can check that — the same unchecked contract `DCHeapRef`
      // already carries across this boundary, now with one more clause. It is
      // filed as GAP-0058 rather than papered over with a comment nobody
      // reads at the call site.
      final ret = cTypeOf(returnType, context: context);
      final ps = params.isEmpty
          ? 'void'
          : params.map((p) => cTypeOf(p.type, context: context)).join(', ');
      return '$ret (*)($ps)';
    case DCStruct(name: final name):
      return name;
  }
}

/// Every distinct struct type appearing in any function signature, in first-
/// seen order.
///
/// KNOWN LIMIT: a struct whose FIELD is another struct is emitted in
/// signature order, which is not necessarily a valid C definition order.
/// Nothing in the language can build that shape today — `@packed` structs
/// hold scalars and pointers only — so this is deliberately not solved
/// ahead of a real case. It is recorded in known-gaps.md GAP-0022 rather
/// than left as a silent trap.
List<DCStruct> _collectStructs(DCModule module) {
  final seen = <String>{};
  final result = <DCStruct>[];
  void visit(DCType type) {
    if (type is DCStruct && seen.add(type.name)) {
      result.add(type);
    }
  }

  for (final function in module.functions) {
    visit(function.returnType);
    function.paramTypes.forEach(visit);
  }
  return result;
}

bool _usesHeapPointer(DCModule module) =>
    _anySignatureType(module, (t) => t is DCHeapPointer);

bool _usesWeakPointer(DCModule module) =>
    _anySignatureType(module, (t) => t is DCWeakPointer);

/// Whether any type in any signature satisfies [test], descending INTO a
/// `DCFuncPtr`'s own parameter and return types (ADR-0060).
///
/// The descent is what makes the two typedef guards above stay correct: a
/// module whose only heap reference is `void Function(Box)`'s parameter still
/// needs `DCHeapRef` defined, and a shallow check would emit a header that
/// mentions an undeclared type. Not extended to `DCPointer`'s pointee, which
/// is a pre-existing shallow check with its own (unrelated) reason to be:
/// `cTypeOf` spells a pointee inline rather than by typedef name.
bool _anySignatureType(DCModule module, bool Function(DCType) test) {
  bool visit(DCType type) {
    if (test(type)) return true;
    if (type is DCFuncPtr) {
      return visit(type.returnType) || type.params.any((p) => visit(p.type));
    }
    return false;
  }

  return module.functions
      .any((f) => visit(f.returnType) || f.paramTypes.any(visit));
}
