/* FFI-header conformance harness (docs/decisions/0034-c-header-emission.md).
 *
 * THE ONE RULE FOR THIS FILE: it contains not a single `extern` prototype
 * and not a single hand-written struct definition for anything crossing the
 * boundary. Every declaration it calls through comes from "ffi.h", which is
 * GENERATED by `dcc build ... --emit-header` from the same DC-IR the object
 * file is emitted from. If this file re-declared the functions by hand it
 * would still link and still pass -- and would prove nothing, since a
 * hand-written prototype agreeing with the object file is what every other
 * example in this repo already demonstrates. The generated header is the
 * subject under test, so it must be the only source of these declarations.
 *
 * There is no checked-in copy of ffi.h: the harness compiles this file with
 * -I pointing at the temp directory it just wrote the header into, so a
 * stale copy cannot mask a regression in the emitter.
 *
 * Exit codes: 0 = every shape correct. Each non-zero code names exactly one
 * check; the mapping is repeated in tests/conformance/ffi-header/run.sh's
 * step 4 comment.
 */
#include <stdint.h>

#include "ffi.h"

int main(void) {
    /* ---- u64 in / u64 out ------------------------------------------- */
    if (ffiAddU64(2, 3) != 5) return 1;
    if (ffiAddU64(0, 0) != 0) return 2;
    /* Both operands and the sum exceed 32 bits, so a uint32_t-wide
     * prototype would truncate rather than accidentally agree. */
    if (ffiAddU64(4000000000ULL, 5000000000ULL) != 9000000000ULL) return 3;

    /* a*b + a~/b + a%b. 7*3=21, 7~/3=2, 7%3=1 -> 24. */
    if (ffiMixU64(7, 3) != 24) return 4;
    /* 1000000*7=7000000, 1000000~/7=142857, 1000000%7=1 -> 7142858. */
    if (ffiMixU64(1000000, 7) != 7142858ULL) return 5;

    /* ---- u32 in / u32 out -------------------------------------------- */
    if (ffiAddU32(2, 3) != 5u) return 6;
    /* Assigning through a uint64_t is what makes the DECLARED width
     * observable: if the header had said uint64_t, whatever the callee
     * left in the upper half of the return register would show up here
     * instead of a clean 0x00000000FFFFFFFE. */
    {
        uint64_t widened = ffiAddU32(0xFFFFFFFCu, 2u);
        if (widened != 0xFFFFFFFEULL) return 7;
    }

    /* ---- u16 in / u16 out -------------------------------------------- */
    /* (a & b) | (a ^ b) == a | b, and neither operand nor result can leave
     * 16 bits, so this is a pure width-mapping check. */
    if (ffiMaskU16(0xFF00u, 0x0FF0u) != (uint16_t)0xFFF0u) return 8;
    {
        uint64_t widened = ffiMaskU16(0xFFFFu, 0x0001u);
        if (widened != 0xFFFFULL) return 9;
    }

    /* ---- u8 in / u8 out ----------------------------------------------
     * Shift amounts are chosen so the mathematical result FITS in 8 bits.
     * That is deliberate and is not a weakened assertion: the backend does
     * not truncate a u8 value to 8 bits on return (see the caveat on
     * ffiShiftU8 in ffi.dart -- `lsl w8, w0, w8; ret`, no masking), so an
     * overflowing shift would be testing that known backend defect, not
     * the header emitter this target exists to verify. The values below
     * still populate all 8 bits, including the top one. */
    if (ffiShiftU8(0x0Fu, 2u) != (uint8_t)0x3Cu) return 10;   /* 0x0F<<2 */
    if (ffiShiftU8(0x7Fu, 1u) != (uint8_t)0xFEu) return 11;   /* top bit set;
                                                               * an int8_t
                                                               * prototype
                                                               * would read
                                                               * this as -2 */
    {
        uint64_t widened = ffiShiftU8(0xFFu, 0u);
        if (widened != 0xFFULL) return 12;
    }

    /* ---- mixed-width parameter list ---------------------------------- */
    /* The u8 parameter is ignored by the callee; what is under test is that
     * the emitter mapped each parameter independently, so the u32 argument
     * lands in the second slot at the right width. */
    if (ffiWidenU8ToU32(0xABu, 123456u) != 123456u) return 13;

    /* ---- struct returned BY VALUE ------------------------------------ */
    {
        Result ok = ffiCheckPositive(42);
        if (ok.tag != 0 || ok.payload != 42) return 14;

        Result err = ffiCheckPositive(0);
        if (err.tag != 1 || err.payload != 999) return 15;

        /* Full 64-bit payload with every byte distinct, so a narrower field
         * or a swapped field order in the generated struct would be caught
         * rather than passing on small values. */
        Result big = ffiCheckPositive(0xDEADBEEFCAFEF00DULL);
        if (big.tag != 0 || big.payload != 0xDEADBEEFCAFEF00DULL) return 16;
    }

    /* ---- struct return through .propagate() -------------------------- */
    {
        Result doubled = ffiDoubleChecked(21);   /* Ok path -> Ok(42) */
        if (doubled.tag != 0 || doubled.payload != 42) return 17;

        Result forwarded = ffiDoubleChecked(0);  /* Err path -> Err(999) */
        if (forwarded.tag != 1 || forwarded.payload != 999) return 18;

        Result always = ffiAlwaysErr(555);       /* always Err -> Err(555) */
        if (always.tag != 1 || always.payload != 555) return 19;
    }

    /* ---- zero-argument functions -------------------------------------
     * These calls compile only because the header declared them. That the
     * declaration is `(void)` and not `()` cannot be asserted from here --
     * C accepts this call site either way -- so it is checked textually by
     * the harness's step 2 instead. */
    if (ffiConstant() != 2718281828ULL) return 20;
    /* 127, not 200: see ffiConstantU8's comment in ffi.dart -- a u8 literal
     * >= 0x80 is returned sign-extended by the current backend, which is a
     * backend defect this target reports rather than a header one it can
     * assert around. */
    if (ffiConstantU8() != (uint8_t)127u) return 21;

    return 0;
}
