/* arith.dart — generated by dcc --emit-header.
 *
 * Do not edit. Regenerate with:
 *   dcc build --mode bare <source>.dart -o <out>.o \
 *     --emit-header <this file>
 *
 * These are ordinary C-ABI symbols: link the .o and call them.
 */
#ifndef DCDART_PLAYGROUND_H
#define DCDART_PLAYGROUND_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

uint64_t mulU64(uint64_t a0, uint64_t a1);
uint32_t mulU32(uint32_t a0, uint32_t a1);
uint16_t mulU16(uint16_t a0, uint16_t a1);
uint8_t mulU8(uint8_t a0, uint8_t a1);
uint64_t divU64(uint64_t a0, uint64_t a1);
uint64_t remU64(uint64_t a0, uint64_t a1);
uint32_t divU32(uint32_t a0, uint32_t a1);
uint32_t remU32(uint32_t a0, uint32_t a1);
uint8_t divU8(uint8_t a0, uint8_t a1);
uint8_t remU8(uint8_t a0, uint8_t a1);
uint64_t gcd(uint64_t a0, uint64_t a1);
uint32_t gcdU32(uint32_t a0, uint32_t a1);
uint64_t digitSum(uint64_t a0);
uint64_t isPrime(uint64_t a0);
uint64_t powMod(uint64_t a0, uint64_t a1, uint64_t a2);
uint64_t lcm(uint64_t a0, uint64_t a1);
uint64_t sumProperDivisors(uint64_t a0);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* DCDART_PLAYGROUND_H */
