/* floatarith.dart — generated by dcc --emit-header.
 *
 * Do not edit. Regenerate with:
 *   dcc build --mode bare <source>.dart -o <out>.o \
 *     --emit-header <this file>
 *
 * These are ordinary C-ABI symbols: link the .o and call them.
 */
#ifndef DCDART_PLAYGROUND_H
#define DCDART_PLAYGROUND_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

double addF64(double a0, double a1);
double subF64(double a0, double a1);
double mulF64(double a0, double a1);
double divF64(double a0, double a1);
float addF32(float a0, float a1);
float subF32(float a0, float a1);
float mulF32(float a0, float a1);
float divF32(float a0, float a1);
double negF64(double a0);
float negF32(float a0);
uint64_t ltF64(double a0, double a1);
uint64_t leF64(double a0, double a1);
uint64_t gtF64(double a0, double a1);
uint64_t geF64(double a0, double a1);
uint64_t eqF64(double a0, double a1);
uint64_t neF64(double a0, double a1);
uint64_t ltF32(float a0, float a1);
double literalF64(void);
float literalF32(void);
double literalFromInt(void);
double widen(float a0);
float narrow(double a0);
float u32ToF32(uint32_t a0);
double u64ToF64(uint64_t a0);
uint32_t truncF32(float a0);
uint64_t truncF64(double a0);
double horner4(double a0);
double geomSum(uint64_t a0, double a1);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* DCDART_PLAYGROUND_H */
