/* loop.dart — generated by dcc --emit-header.
 *
 * Do not edit. Regenerate with:
 *   dcc build --mode bare <source>.dart -o <out>.o \
 *     --emit-header <this file>
 *
 * These are ordinary C-ABI symbols: link the .o and call them.
 */
#ifndef DCDART_PLAYGROUND_H
#define DCDART_PLAYGROUND_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

uint64_t sumTo(uint64_t a0);
uint64_t firstAtLeast(uint64_t a0, uint64_t a1);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* DCDART_PLAYGROUND_H */
