#!/usr/bin/env bash
# vendor-frontend.sh — reproduce core/frontend/vendor/dart-sdk/ from scratch.
#
# WHY THIS EXISTS
#
# core/frontend/vendor/ is .gitignore'd (~212M working tree + its own nested
# .git). That keeps this repo's size sane, but it means a FRESH CLONE OF THIS
# REPO CANNOT `pub get`, let alone build: dcc-lower has a path dependency on
# the vendored `pkg/kernel`, so every package in the pipeline fails to resolve
# until the vendor is restored.
#
# Restoring it is two steps, not one, and the second is easy to miss:
#
#   1. The sparse/shallow/partial clone decided in ADR-0005.
#   2. The workspace-detach pubspec edits decided in ADR-0007 — upstream's
#      three pubspecs declare `resolution: workspace`, which makes `pub get`
#      demand all ~60 members of dart-lang/sdk's pub workspace be physically
#      present. Those edits live only in the ignored tree, so a re-clone
#      silently reverts them. ADR-0007's own Consequences section flagged this
#      ("the detach is not a one-time patch that survives a re-clone... Worth a
#      small script if re-vendoring becomes routine; not written now since it's
#      happened exactly once"). It has now happened a second time, on a new
#      machine, which is what prompted this script. See known-gaps.md GAP-0021.
#
# Idempotent: re-running re-applies the pubspec edits without re-cloning.
#
# Usage:  bash core/scripts/vendor-frontend.sh [--force]
#           --force  delete and re-clone an existing vendor tree
#
# Exit status: 0 on success, non-zero with a specific message otherwise.

set -euo pipefail

# Pin from ADR-0007 (re-pinned from ADR-0005's `main` commit to a release tag,
# so the vendored pkg/front_end declares `sdk: ^3.12.0-0` and resolves against
# a stable SDK instead of requiring a dev-channel prerelease).
readonly TAG="3.12.2"
readonly PINNED_COMMIT="d684a576a6aa954ae107a03b2b4e1d61c3bebe93"
readonly UPSTREAM="https://github.com/dart-lang/sdk.git"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VENDOR_DIR="$CORE_DIR/frontend/vendor"
SDK_DIR="$VENDOR_DIR/dart-sdk"
PKG_DIR="$SDK_DIR/pkg"

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

die() { echo "vendor-frontend: FAIL — $1" >&2; exit 1; }

command -v git >/dev/null 2>&1 || die "git not found on PATH"

# ---------------------------------------------------------------------------
# Step 1 — sparse/shallow/partial clone (ADR-0005), pinned to a tag (ADR-0007).
# ---------------------------------------------------------------------------
if [[ $FORCE -eq 1 && -d "$SDK_DIR" ]]; then
  echo "vendor-frontend: --force, removing existing $SDK_DIR"
  rm -rf "$SDK_DIR"
fi

if [[ -d "$SDK_DIR/.git" ]]; then
  echo "vendor-frontend: vendor tree already present, skipping clone (use --force to re-clone)"
else
  mkdir -p "$VENDOR_DIR"
  echo "vendor-frontend: cloning dart-lang/sdk @ $TAG (sparse: pkg/front_end, pkg/kernel, pkg/_fe_analyzer_shared)"
  git clone --filter=blob:none --sparse --depth=1 --branch "$TAG" "$UPSTREAM" "$SDK_DIR"
  ( cd "$SDK_DIR" && git sparse-checkout set pkg/front_end pkg/kernel pkg/_fe_analyzer_shared )
fi

ACTUAL_COMMIT="$(cd "$SDK_DIR" && git rev-parse HEAD)"
if [[ "$ACTUAL_COMMIT" != "$PINNED_COMMIT" ]]; then
  die "vendor is at $ACTUAL_COMMIT, expected ADR-0007's pin $PINNED_COMMIT"
fi
echo "vendor-frontend: commit pin OK ($PINNED_COMMIT)"

for p in front_end kernel _fe_analyzer_shared; do
  [[ -d "$PKG_DIR/$p" ]] || die "sparse checkout is missing pkg/$p"
done

# ---------------------------------------------------------------------------
# Step 2 — the workspace-detach edits (ADR-0007 decision item 2).
#
# Rewritten wholesale rather than patched, so this is idempotent and survives
# a --force re-clone. Upstream's dev_dependencies are dropped deliberately:
# this fork does not run front_end's own upstream test suite (DCDart's tests
# live in core/tests/conformance/), and those dev deps pull in analyzer,
# dart2wasm, compiler, vm, ... none of which are vendored here.
# ---------------------------------------------------------------------------
echo "vendor-frontend: applying ADR-0007 workspace-detach pubspec edits"

cat > "$PKG_DIR/_fe_analyzer_shared/pubspec.yaml" <<'EOF'
# DCDart fork note (docs/decisions/0007-detach-vendored-frontend-from-sdk-workspace.md):
# `resolution: workspace` and the upstream dev_dependencies are removed so this
# package resolves standalone, outside dart-lang/sdk's ~60-member pub workspace.
# Regenerated by core/scripts/vendor-frontend.sh — do not hand-edit.
name: _fe_analyzer_shared
version: 98.0.0
description: Logic that is shared between the front_end and analyzer packages.
repository: https://github.com/dart-lang/sdk/tree/main/pkg/_fe_analyzer_shared

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.9.0
  source_span: ^1.10.0
EOF

cat > "$PKG_DIR/kernel/pubspec.yaml" <<'EOF'
# DCDart fork note (docs/decisions/0007-detach-vendored-frontend-from-sdk-workspace.md):
# `resolution: workspace` and the upstream dev_dependencies are removed; the
# `_fe_analyzer_shared` dep is a path dep to the vendored sibling.
# Regenerated by core/scripts/vendor-frontend.sh — do not hand-edit.
name: kernel
publish_to: none

environment:
  sdk: '^3.12.0-0'

dependencies:
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
EOF

cat > "$PKG_DIR/front_end/pubspec.yaml" <<'EOF'
# DCDart fork note (docs/decisions/0007-detach-vendored-frontend-from-sdk-workspace.md):
# `resolution: workspace`, `workspace: [testcases]` and the upstream
# dev_dependencies are removed; the two vendored siblings are path deps and
# package_config/yaml resolve as ordinary hosted deps.
# Regenerated by core/scripts/vendor-frontend.sh — do not hand-edit.
name: front_end
publish_to: none

environment:
  sdk: '^3.12.0-0'

dependencies:
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
  kernel:
    path: ../kernel
  package_config: any
  yaml: any
EOF

# ---------------------------------------------------------------------------
# Step 3 — prove it actually resolves, rather than assuming it does.
# ---------------------------------------------------------------------------
if command -v dart >/dev/null 2>&1; then
  echo "vendor-frontend: resolving core/ packages ($(dart --version 2>&1))"
  for p in dc-ir dc-elide dcc-lower backend dcc dc-objdump; do
    ( cd "$CORE_DIR/$p" && dart pub get >/dev/null 2>&1 ) \
      || die "dart pub get failed in core/$p (a Dart SDK satisfying ^3.12.0-0 is required)"
    echo "  pub get OK  core/$p"
  done
  # -------------------------------------------------------------------------
  # Step 4 — COMPILE SOMETHING. `pub get` succeeding is not the claim anyone
  # cares about.
  #
  # For its whole life this script's last word was "prove it actually
  # resolves", and it proved dependency resolution. Nobody had ever
  # established that a clean checkout could COMPILE A PROGRAM -- so
  # "DCDart is reproducible from git" was an untested assertion, and when a
  # downstream toolchain failed to build, the reasonable conclusion available
  # from the evidence was that no commit identified a buildable compiler at
  # all. It does; nothing said so.
  #
  # That is the same defect this project has been removing all day, one level
  # below the code: A CHECK THAT VALIDATES SOMETHING ADJACENT TO WHAT MATTERS.
  #
  # The import below is an ABSOLUTE path to this checkout's own prelude, and
  # that is load-bearing rather than convenient.
  #
  # `dcc` decides `@bare` by comparing the annotation's library `importUri`
  # against the prelude Uri from `pipeline.dart`'s `_resolvePreludeUri()`,
  # which is `Platform.script.resolve(...)`. That is EXACT Uri EQUALITY ON A
  # LEXICALLY NORMALISED PATH: `..` segments are folded, and symlinks are
  # resolved on NEITHER side. So two spellings of the same file are two
  # different libraries, every `@bare` annotation in the "wrong" one becomes
  # invisible, and the error is `no @bare top-level function found` -- which
  # reads as a broken compiler rather than a path mismatch.
  #
  # Stated precisely because the imprecise version cost real work: this was
  # described (here and in a downstream repo) as resolution through REAL
  # paths, which made a symlinked toolchain look impossible in principle and
  # sent several agents copying 211 MB instead. Under the actual rule a
  # symlink is fine, provided both sides spell the path the same way.
  echo "vendor-frontend: proving the toolchain can COMPILE, not just resolve"
  SMOKE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/dcdart-smoke.XXXXXX")" \
    || die "could not create a temp dir for the build proof"
  cat > "$SMOKE_DIR/smoke.dart" <<SMOKE
import '$CORE_DIR/runtime/dc-core-bare/prelude.dart';

@bare u64 smokeAdd(u64 a, u64 b) => a + b;
SMOKE
  if ( cd "$CORE_DIR" && dart dcc/bin/dcc.dart build --mode bare --target host \
         "$SMOKE_DIR/smoke.dart" -o "$SMOKE_DIR/smoke.o" ) \
       > "$SMOKE_DIR/build.log" 2>&1; then
    if [ -s "$SMOKE_DIR/smoke.o" ]; then
      echo "  build OK    $(wc -c < "$SMOKE_DIR/smoke.o" | tr -d ' ') bytes of object emitted"
    else
      cat "$SMOKE_DIR/build.log" >&2
      rm -rf "$SMOKE_DIR"
      die "dcc reported success but emitted no object — this checkout does NOT build"
    fi
  else
    cat "$SMOKE_DIR/build.log" >&2
    rm -rf "$SMOKE_DIR"
    die "this checkout resolves but does NOT compile. If the error is 'no @bare top-level function found', the prelude was reached by a different real path than dcc expects (see the note above this check) rather than the compiler being broken."
  fi
  rm -rf "$SMOKE_DIR"
else
  echo "vendor-frontend: WARNING — no 'dart' on PATH, skipping the pub-get and build proofs." >&2
  echo "vendor-frontend: install a Dart SDK satisfying ^3.12.0-0 and re-run to verify." >&2
fi

echo "vendor-frontend: done — core/frontend/vendor/dart-sdk/ restored at $TAG"
