#!/usr/bin/env bash
# verify-freestanding.sh — the spine of the DCDart project.
#
# A @bare object file must link with no runtime. This script is the mechanical
# guarantee of that. A green test suite with a leaked runtime symbol is a FAILED
# change. Run it on every @bare change and every backend change.
#
# Usage: scripts/verify-freestanding.sh build/kernel.o [more.o ...]
#
# ---------------------------------------------------------------------------
# EXTERN MANIFESTS (ADR-0038, docs/escalations/0003-extern-c-calls-vs-
# freestanding.md).
#
# RATIFIED: the project owner decided option 2 on 2026-08-20. That decision
# reached this file relayed through another agent session working in this
# tree, not witnessed firsthand — recorded that way because a change to the
# meaning of CLAUDE.md rule 1 should say on its face where it came from.
#
# Escalation 0003 asked whether an object that deliberately calls an external
# C symbol can still satisfy rule 1, given that calling one MEANS carrying an
# undefined symbol. Its recommendation — option 2, implemented here — is that
# the check distinguishes:
#
#   * a symbol the COMPILER put there without anyone asking (dc_alloc,
#     dc_throw, dc_orc_*, Dart_*) — still a hard failure, always; from
#   * a symbol the AUTHOR declared by name in the source with
#     `@extern external`, which dcc records in <objfile>.externs.
#
# So this script now permits exactly the names in <objfile>.externs, in
# addition to the allowlist, and REPORTS them on every pass so they are
# visible in the log rather than silent (escalation 0003's own first
# condition). The allowlist is untouched and still owned by E4.
#
# What has NOT been weakened: an undefined symbol with no manifest entry and
# no allowlist entry is still a hard failure, and an object with no manifest
# behaves exactly as it did before this existed. Delete an object's manifest
# and its extern calls fail the check again — the conformance harness
# tests exactly that.
#
# Residual risk, stated rather than hidden: the manifest is generated by dcc,
# so it always agrees with the source it was built from, and a hand-written
# manifest could launder a symbol. That is the same trust model the allowlist
# already has. Embedding the declaration set inside the object instead was
# considered and deferred, not forgotten -- see ADR-0038's rejected
# alternatives, and escalation 0003's "what ratification did not settle".
# ---------------------------------------------------------------------------

set -euo pipefail

ALLOWLIST="${DCDART_ALLOWLIST:-tools/bare-symbol-allowlist.txt}"
NM="${NM:-llvm-nm}"

if [[ $# -eq 0 ]]; then
  echo "usage: $0 <objfile> [objfile ...]" >&2
  exit 2
fi

if [[ ! -f "$ALLOWLIST" ]]; then
  echo "FATAL: allowlist not found at $ALLOWLIST" >&2
  echo "The allowlist is owned by E4 (kernel). Do not create one to make this pass." >&2
  exit 2
fi


# ---------------------------------------------------------------------------
# PORTABILITY: this script must run on a STOCK macOS shell.
#
# `mapfile`/`readarray` are bash 4+. macOS ships bash 3.2.57, so on a stock Mac
# every `mapfile` here failed with "command not found". Because `set -e` is on,
# the script aborted and the caller saw a FAIL -- the safe direction, but only
# by accident. Without `set -e`, `undef` would have been empty, the loop over it
# would have examined nothing, and the script would have printed
# `FREESTANDING: pass` having checked zero symbols. That is a vacuous pass on
# the one check CLAUDE.md calls the project's spine.
#
# A second bash 3.2 trap, which the fix must also survive: under `set -u`,
# bash before 4.4 treats `"${arr[@]}"` on an EMPTY array as an unbound variable
# and aborts. So every expansion of a possibly-empty array below uses the
# `${arr[@]+"${arr[@]}"}` idiom rather than a bare one.
_read_lines() {           # usage: _read_lines <arrayname>   (input on stdin)
  local __name="$1" __line
  eval "$__name=()"
  while IFS= read -r __line || [[ -n "$__line" ]]; do
    [[ -z "$__line" ]] && continue
    eval "$__name+=(\"\$__line\")"
  done
}

# Strip comments and blanks from the allowlist.
_read_lines ALLOWED < <(grep -vE '^[[:space:]]*(#|$)' "$ALLOWLIST" | sed 's/[[:space:]]*$//')

# NO non-vacuity guard on this array, deliberately. An empty ALLOWED is the
# INTENDED state, not a parse failure: every entry in the shipped allowlist is
# commented out, because the freestanding baseline is genuinely zero undefined
# symbols and the file's own header says not to grow it to make a check pass.
# A guard here treating "zero entries" as a broken parse was written and
# removed within the hour -- it turned the correct configuration into a hard
# FATAL. Worth leaving this note: a vacuity guard is only correct where the
# empty case is genuinely impossible, and asserting non-emptiness of something
# designed to be empty is the same defect as a vacuous pass, pointed the other
# way.

# ---------------------------------------------------------------------------
# RESERVED RUNTIME FAMILIES — never honorable, by allowlist OR by manifest.
#
# This closes a hole between this script's stated contract and what it did.
# The header above says these families are "still a hard failure, always",
# and ADR-0038/escalation 0003's ratified wording says the check "keeps
# catching dc_alloc, dc_throw, dc_orc_* and Dart_* exactly as before". It did
# not: a manifest listing `dc_alloc` or `Dart_EnterScope` made the check
# report `FREESTANDING: pass`. Verified by hand before this was added.
#
# Why these specifically cannot be declared away: every other undefined
# symbol is a claim about SOMEONE ELSE'S object file, which an author is
# entitled to make. These four families are claims about OUR OWN runtime —
# they appear because the compiler emitted them, and their own diagnostics
# say so ("This is a backend bug. Escalate to E2 immediately."). A program
# that declares `@extern external dc_alloc` is not expressing a dependency,
# it is silencing the one check that would have caught the language smuggling
# a runtime into @bare. No legitimate program calls Dart_EnterScope.
#
# Deliberately NOT configurable and not overridable. A safety property with an
# escape hatch is a safety property that will be escaped.
RESERVED=(
  'dc_alloc' 'dc_free' 'dc_realloc'
  'dc_throw' 'dc_unwind' '__gxx_personality*'
  'dc_orc_*'
  'dart_*' 'Dart_*'
)

is_reserved() {
  local sym="$1" pat
  for pat in "${RESERVED[@]}"; do
    # shellcheck disable=SC2053
    if [[ "$sym" == $pat ]]; then return 0; fi
  done
  return 1
}

fail=0

for obj in "$@"; do
  [[ -f "$obj" ]] || { echo "FATAL: no such object: $obj" >&2; exit 2; }

  # Declared externs for THIS object, if any. Exact names only -- no globs.
  # A glob here would let one declaration cover symbols the source never
  # named, which is exactly the drift escalation 0003 warns about.
  DECLARED=()
  MANIFEST="$obj.externs"
  if [[ -f "$MANIFEST" ]]; then
    _read_lines DECLARED < <(grep -vE '^[[:space:]]*(#|$)' "$MANIFEST" | sed 's/[[:space:]]*$//')
  fi

  # Undefined symbols only.
  #
  # NON-VACUITY GUARD, and this is the one that matters most in this file.
  # Everything below concludes from the ABSENCE of a symbol in `undef`, so an
  # `nm` that failed to run -- wrong binary, unreadable format, a shell without
  # `mapfile` -- yields an empty list and a confident `FREESTANDING: pass` that
  # examined nothing. `nm`'s exit status is therefore checked BEFORE its output
  # is trusted, and a failure is a hard error rather than a quiet pass.
  set +e
  NM_OUT="$("$NM" -u --format=posix "$obj" 2>&1)"
  NM_STATUS=$?
  set -e
  if (( NM_STATUS != 0 )); then
    echo "FATAL: \"$NM -u\" exited $NM_STATUS on $obj. Not reporting a pass: this check concludes from the ABSENCE of undefined symbols, so a broken nm would look identical to a clean object." >&2
    echo "$NM_OUT" | head -5 >&2
    exit 2
  fi
  _read_lines undef < <(printf '%s\n' "$NM_OUT" | awk '{print $1}' | sed 's/^_//')

  leaked=()
  honored=()
  for sym in ${undef[@]+"${undef[@]}"}; do
    [[ -z "$sym" ]] && continue
    ok=0
    # Checked FIRST, so neither the allowlist nor the manifest can honor it.
    if is_reserved "$sym"; then
      leaked+=("$sym")
      continue
    fi
    for a in ${ALLOWED[@]+"${ALLOWED[@]}"}; do
      # Allowlist entries may be exact names or shell globs (e.g. __aeabi_*).
      # shellcheck disable=SC2053
      if [[ "$sym" == $a ]]; then ok=1; break; fi
    done
    if (( ! ok )); then
      for d in ${DECLARED[@]+"${DECLARED[@]}"}; do
        if [[ "$sym" == "$d" ]]; then ok=1; honored+=("$sym"); break; fi
      done
    fi
    (( ok )) || leaked+=("$sym")
  done

  # A manifest entry that no undefined symbol matches means the manifest and
  # the object disagree -- a stale manifest, a renamed symbol, or a call the
  # optimizer removed. Report it, but do not fail: it PERMITS nothing, so it
  # cannot hide a leak. Silence would be worse than noise here.
  for d in ${DECLARED[@]+"${DECLARED[@]}"}; do
    [[ -z "$d" ]] && continue
    found=0
    for sym in ${undef[@]+"${undef[@]}"}; do
      if [[ "$sym" == "$d" ]]; then found=1; break; fi
    done
    (( found )) || echo "  note: declared extern \"$d\" is not undefined in $obj (stale manifest entry?)"
  done

  if (( ${#leaked[@]} )); then
    fail=1
    echo "FREESTANDING: FAIL  $obj"
    for sym in ${leaked[@]+"${leaked[@]}"}; do
      case "$sym" in
        dc_alloc|dc_free|dc_realloc)
          echo "  $sym  -> implicit allocation. A closure escaped, a String was built, or a collection grew." ;;
        dc_throw|dc_unwind|__gxx_personality*)
          echo "  $sym  -> a throw reached @bare, usually via a @hosted library call." ;;
        dc_orc_*)
          echo "  $sym  -> cycle collector reference. A @hosted type leaked into @bare." ;;
        dart_*|Dart_*)
          echo "  $sym  -> OLD VM RUNTIME. This is a backend bug. Escalate to E2 immediately." ;;
        *)
          echo "  $sym  -> undefined, not allowlisted, and not declared @extern in the source." ;;
      esac
    done
    echo "  Do NOT add to the allowlist to make this pass. The allowlist is owned by E4."
    echo "  If this symbol is a deliberate C dependency, declare it in the DCDart"
    echo "  source as \`@extern external ...\` so dcc records it (ADR-0038)."
    for sym in ${leaked[@]+"${leaked[@]}"}; do
      if is_reserved "$sym"; then
        echo "  NOTE: \"$sym\" is a RESERVED runtime name. Declaring it @extern will"
        echo "  NOT make this pass — these families are never honorable, because their"
        echo "  presence means the compiler emitted them, not that you asked for them."
        break
      fi
    done
  else
    if (( ${#honored[@]} )); then
      echo "FREESTANDING: pass  $obj  (${#honored[@]} declared extern(s): ${honored[*]})"
    else
      echo "FREESTANDING: pass  $obj"
    fi
  fi
done

exit $fail
